### ISSUE TITLE
Fractal modules should be able to utilize generators other than Perlin

### ISSUE THREAD

**Issue by mystise** [Razaekel/noise-rs#159]
Not certain exactly how to implement this, but it'd be really nice if the fractal modules were combinators instead of generators, so that you could make Open Simplex fBm and so on.

**Comment by Razaekel** [comment]
I have an idea for how to implement this, but I need to test it out.

**Comment by jeffparsons** [comment]
@Razaekel Would you mind briefly summarising your idea here? With a bit of luck, somebody else might find time to implement it! 🙏
