### ISSUE TITLE
Analytical derivitives for SuperSimplex noise

### ISSUE THREAD

**Issue by kelvin13** [Razaekel/noise-rs#167]
Does anyone know how to compute the analytic derivative of SuperSimplex noise? The algorithm is so poorly documented I couldn’t find any information anywhere.

**Comment by adudney** [comment]
Checkout the eval_D2C1 and eval_D3C1 functions from SuperSimplexNoise.java, those provide what appears to be dx, dy, and dxdy, and all the other various derivatives.

**Comment by kelvin13** [comment]
yikes

**Comment by adudney** [comment]
The derivatives for only one contribution (so you can just add them together after accounting for the different x and y positions, as in the eval_D2C1 and eval_D3C1 functions) are:

![screen shot 2017-05-29 at 23 05 48](https://cloud.githubusercontent.com/assets/246232/26570096/791d60e0-44c3-11e7-8cd9-d3e25dcddf95.png)

**Comment by kelvin13** [comment]
are `x` and `y` relative to the gradient point

**Comment by adudney** [comment]
Yes
