### ISSUE TITLE
No method named `get`

### ISSUE THREAD

**Issue by David-OConnor** [Razaekel/noise-rs#194]
Following the lone example in the documentation: no method named `get` found for type `noise::OpenSimplex` in the current scope. Note that the readme points to noise::noise_fns, which is private, while the Docs page points to calling the noise types directly, which leads to this error. Note that these are the only use examples I could find in the readme and Docs site.

**Comment by syberant** [comment]
Looking for [this method](https://docs.rs/noise/0.5.1/noise/trait.NoiseFn.html#tymethod.get)? `OpenSimplex` implements this trait multiple times: for [2D](https://docs.rs/noise/0.5.1/noise/struct.OpenSimplex.html#impl-NoiseFn%3CPoint2%3Cf64%3E%3E), [3D](https://docs.rs/noise/0.5.1/noise/struct.OpenSimplex.html#impl-NoiseFn%3CPoint3%3Cf64%3E%3E), and [4D](https://docs.rs/noise/0.5.1/noise/struct.OpenSimplex.html#impl-NoiseFn%3CPoint4%3Cf64%3E%3E).

Bring the trait into scope with `use noise::NoiseFn;`

When calling with a `Point2<f64>` (`[f64; 2]`) it uses the 2D implementation, when calling with a `Point3<f64>` it uses the 3D implementation, and when calling with a `Point4<f64>` it uses the 4D implementation.
