### ISSUE TITLE
How would I return a noise function such as ScaleBias from a function?

### ISSUE THREAD

**Issue by nrayamajhee** [Razaekel/noise-rs#195]
I am trying to separate parts of the complex planet example into difference functions instead of writing a rather long and boring main function. How would I go about doing it? I am new to rust, and I often find myself struggling with rust's lifetime annotations.

Since noise functions such as ScaleBias and Clamp hold reference to the source noise function, is it possible to write a function that creates Fbm inside it, layers multiple noises such as ScaleBias and/or Clamp and return the resulting noise function?

**Comment by half-potato** [comment]
Wait but how do you do this?
