### ISSUE TITLE
`Invert` is poorly named; should be renamed "Negate"

### ISSUE THREAD

**Issue by Lucretiel** [Razaekel/noise-rs#202]
https://github.com/Razaekel/noise-rs/blob/4606a00c10fb10fb1619bb2a51d5868f20227674/src/noise_fns/modifiers/invert.rs#L3

The modifier Noise called "invert" should be renamed "negate". Invert generally means "1/X", not "-X"

**Comment by Atul9** [comment]
@Razaekel @Lucretiel I have opened up a PR for this - #204

**Comment by Razaekel** [comment]
Some image manipulation programs have a feature called 'Invert Colors' or similar. Visually, this is a better representation of what this function does when using color gradients to visualize the result.

Using the term Negate doesn't provide as clear of a visual image of what the function would do when reading just the name.

**Comment by Lucretiel** [comment]
Invert colors is the equivalent of `COLOR_MAX - component`, right? They're both a subtraction, but they don't seem to be directly compatible?

**Comment by cheako** [comment]
I agree, images and colors go together.  Colors cannot be negative, but noise can.  Also noise is not colorful.  Likewise the inverse of addition is subtraction, but the inverse of multiplication is division and as such the inverse of a number is None.  Therefore Negate is the word you are looking for.
