### ISSUE TITLE
Could I help with crate maintenance?

### ISSUE THREAD

**Issue by austinjones** [Razaekel/noise-rs#208]
Hi @Razaekel,
The breadth of support for noise functions and transformations in this crate is really cool!

There are a few open PRs that I'd be interesting in seeing merged (particularly #203).  Is there anything I could do to help out with maintenance for this crate?

I'm also interesting in adding an implementation of Wavelet noise, which some very nice properties for 3d rendering, and great performance in low frequency bands.
-Austin

**Comment by aeubanks** [comment]
+1, the last release on https://crates.io/crates/noise was over a year ago.
It'd be nice to have a release with #203 so there's no need to override the exact version of "noise" in Cargo.toml with a specific commit.

**Comment by kaimast** [comment]
It would be great if a new version of this crate could be release soon. Version 0.6 uses a super outdated version of the `image` crate. See the output of `cargo audit` below:

```
error: Vulnerable crates found!

ID:       RUSTSEC-2019-0014
Crate:    image
Version:  0.18.0
Date:     2019-08-21
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0014
Title:    Flaw in interface may drop uninitialized instance of arbitrary types
Solution:  upgrade to >= 0.21.3
Dependency tree:
image 0.18.0
└── noise 0.6.0
```
