### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by bvssvni** [Razaekel/noise-rs#22]
There is little documentation in the library...

**Comment by Cifram** [comment]
Do you consider the recent update to README.md sufficient?

**Comment by bjz** [comment]
I think we need to move the README docs into doc comments

**Comment by Cifram** [comment]
I think adding the doc comments would be useful, but not as a replacement for the README. The doc comments are great for explaining a thing once you're looking at it, but the README gives the overview of what to look at.

That said, I think the README could still be a good deal better organized. We could potentially remove most of the function signatures from the README and replace them with links to rust-doc. Then the README would just serve as a quick reference for what types of noise functions are available.

**Comment by bjz** [comment]
Yeah, I think the README might be better if it had a high level overview with a simple example.

**Comment by David-OConnor** [comment]
It would be nice to have an example for each part of API coverage.
