### ISSUE TITLE
Complie Error

### ISSUE THREAD

**Issue by lukeacat** [Razaekel/noise-rs#225]
`error[E0432]: unresolved imports `rand::Rand`, `rand::XorShiftRng`
  --> /home/kuteshi/.cargo/registry/src/github.com-1ecc6299db9ec823/noise-0.1.5/src/seed.rs:18:12
   |
18 | use rand::{Rand, Rng, SeedableRng, XorShiftRng};
   |            ^^^^                    ^^^^^^^^^^^ no `XorShiftRng` in the root
   |            |
   |            no `Rand` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `noise`.
`
Using latest Nightly

**Comment by Razaekel** [comment]
v0.1.5 is extremely old. it was released May 3, 2015.

You should try with v0.5.0+
