### ISSUE TITLE
Default lacunarity of fractal noise

### ISSUE THREAD

**Issue by mfiano** [Razaekel/noise-rs#240]
Hello and thank you for this library. I was just wondering why the default lacunarity value was changed in commit a3e1a1a4737e5e9a6950da996dbe2483aef583f3 from `2.0` to `2.09...` which is different than any other noise library I've seen. Does this have to do with integral coordinate sampling being 0 for Perlin or something? Thanks!

**Comment by Razaekel** [comment]
Pretty much. Perlin noise is 0 along the integer value coordinates and having a lacunarity of 2 means that higher octaves with sampled coordinates that are along integer coordinates that are multiples of 2 will overlap and can make the regularity of Perlin noise more obvious. Using an irrational number that is close to 2 prevents the overlapping and helps hide the regularity of Perlin noise.

**Comment by mfiano** [comment]
That's what I assumed and it makes total sense. Thanks for the quick answer :+1:
