### ISSUE TITLE
Perlin noise generator returns only 0

### ISSUE THREAD

**Issue by fenjalien** [Razaekel/noise-rs#248]
The following code for me prints 0 for each value
```rust
use noise::{NoiseFn, Perlin, Seedable};

fn main() {
    let perlin = Perlin::new().set_seed(100);

    for x in 0..10 {
        for y in 0..10 {
            println!("({}, {}) = {}", x, y, perlin.get([x as f64, y as f64]));
        }
    }
}
```
The active toolchain is `stable-x86_64-unknown-linux-gnu` with `rustc` at version `1.52.1`
Other generators like `Value` and `OpenSimplex` don't have this behaviour. Changing the seed and version of `noise-rs` doesn't help.

**Comment by Razaekel** [comment]
Perlin noise produces zero values when sampled along lattice coordinates, i.e. at integer values for `x` or `y`. To resolve this, you could add an offset to the sampled coordinates, something like:

```rust
perlin.get([x as f64 + 0.5, y as f64 + 0.5]);
```

I'll have to add a note stating this zero result at lattice coordinates for the future.
