### ISSUE TITLE
Regression: Value noise is generating very large position-dependent values since 0.8

### ISSUE THREAD

**Issue by kpreid** [Razaekel/noise-rs#294]
When I updated from `0.7.0` to `0.8.1` all my uses of `noise::Value` started producing much larger numbers, which increase in magnitude away from the origin.

On examining the code, it looks like this is a newly introduced operator precedence error: `0.7.0` has in `src/noise_fns/generators/value.rs`

```rust
let weight = math::map2(math::sub2(point, floored), interpolate::s_curve5);
```

whereas `0.8.1` has in `src/noise/core/value.rs`

```rust
let weight = point - floored.map_quintic();
```

which I am guessing should instead be 

```rust
let weight = (point - floored).map_quintic();
```

**Comment by Razaekel** [comment]
Thank you for pointing this out. v0.8.2 is released with fix included.
