### ISSUE TITLE
Fbm returns value outside of [-1, 1]

### ISSUE THREAD

**Issue by Laocoon7** [Razaekel/noise-rs#329]
`fbm.rs#181` state `// Scale the result into the [-1,1] range`

```rust
let noise_gen = noise::Fbm::<noise::Perlin>::new(0);
let x = 29.0 * 0.03 + 0.6;
let y = 2.0 * 0.03 + 0.6;
let result = noise::NoiseFn::get(&noise_gen, [x, y]);
panic!("{}", result);
```

I would assume result should be between [-1, 1] from the comment, and most noise libraries generating normalized outputs, however the value I receive is `1.0948304546272307`

**Comment by manankarnik** [comment]
I looked at it and it has been fixed in commit https://github.com/Razaekel/noise-rs/commit/85e478652d911595eb4066fc3fce7aa103b8ada8, however it is not released yet.

**Comment by Razaekel** [comment]
Seconding what @manankarnik  says.
