### ISSUE TITLE
Unexpected smooth noise in unreleased version

### ISSUE THREAD

**Issue by vallentin** [Razaekel/noise-rs#334]
I was in the need for #308, so I used the repo as a git dependency. I noticed, that the output is vastly different all of a sudden.

Using `Fbm<OpenSimplex>`, then `noise = "0.8"` produces:

![20230829_014111](https://github.com/Razaekel/noise-rs/assets/17464404/a0d28ebe-1265-4b2b-ad84-6513ae83febd)

While using `noise = { git = "https://github.com/Razaekel/noise-rs" }` produces:

![20230829_014037](https://github.com/Razaekel/noise-rs/assets/17464404/4179b45f-ba3a-4ee3-9125-405f521b0ab9)

The unreleased version produces an output that is a lot more smoother, with a much smaller output range. I took the noise value and scaled it by `val = noise.get([x, y]) * 0.75 + 0.5`, then I used `val` as the input for a jet colormap.

I would almost say, the unreleased version produces a noise output, that looks like the `Fbm` isn't even used, and it's just `OpenSimplex`.

I understand that I'm using unreleased code, but I just wanted to address it, in case this wasn't noticed, and is unintentional.

**Comment by PrinceOfBorgo** [comment]
The problem should have been solved as part of #342 (merging commits of #339)
