### ISSUE TITLE
Perlin noise always returns 0 on whole numbers

### ISSUE THREAD

**Issue by doonv** [Razaekel/noise-rs#337]
I don't know what I am doing wrong but perlin noise always returns zero on whole numbers:
```rs
let noise = noise::Perlin::new(123578);

println!("{}", noise.get([2.0, 1.0]));
println!("{}", noise.get([2.0, 124.0]));
println!("{}", noise.get([2.0, 12.0]));

// With decimals:
println!("{}", noise.get([2.3, 12.1]));
```
Which results in:
```rs
0
0
0
0.33866112622786926
```
Is this intended behavior? I don't think so.

**Comment by PrinceOfBorgo** [comment]
Yes, it is the intended behaviour. More info [here](https://gamedev.stackexchange.com/questions/166124/perlin-noise-generation-always-returning-zero).

**Comment by doonv** [comment]
> Yes, it is the intended behaviour. More info [here](https://gamedev.stackexchange.com/questions/166124/perlin-noise-generation-always-returning-zero).

Ah thanks, you should add that to the documentation.
