### ISSUE TITLE
Possible typo in Turbulence docs?

### ISSUE THREAD

**Issue by afonsolage** [Razaekel/noise-rs#346]
While reading `Turbulence` docs, I didn't understood what `_` means. Is this a typo?

https://github.com/Razaekel/noise-rs/blob/95c6bc435cbafd0e8f90314a34a1484c2a5baa13/src/noise_fns/transformers/turbulence.rs#L6

**Comment by PrinceOfBorgo** [comment]
It seems so.  For some reason `_Turbulence_` has been replaced with just `_` [in this commit](https://github.com/Razaekel/noise-rs/commit/a3e1a1a#diff-f7e9df42f387f21e09ef2cdfd9666f16ff329a4011ed5215507f04a61974caeeL16).
